# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

env:
  WORKSPACE_PATH: frontend/authentication

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 'Checkout: ${{ github.ref }}'
        with:
          fetch-depth: 0
    
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Packages CI
        run: |
          cd $WORKSPACE_PATH && npm ci
    
      - name: React Build
        run: |
          cd $WORKSPACE_PATH && npm run build --if-present

      - name: Run Tests
        run: |
          cd $WORKSPACE_PATH && npm test
